CREATE DATABASE LivrosBD;
GO

USE LivrosBD;
GO

CREATE TABLE Genero(
	IdGenero INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Livro(
	IdLivro INT PRIMARY KEY IDENTITY,
	Imagem VARCHAR(100),
	Titulo VARCHAR(100) NOT NULL,
	IdGenero INT FOREIGN KEY REFERENCES Genero(IdGenero),
	Autor VARCHAR(100) NOT NULL,
	Ano INT NOT NULL
);
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL
);
GO

SELECT * FROM Genero

SELECT * FROM Livro

SELECT * FROM Usuario


